/**
 * @see https://unpkg.com/browse/tree-sitter-wasms@latest/out/
 */
export const ext2Lang = {
  vue: 'vue',
  cjs: 'javascript',
  mjs: 'javascript',
  mjsx: 'javascript',
  js: 'javascript',
  jsx: 'javascript',
  ctx: 'typescript',
  mts: 'typescript',
  mtsx: 'typescript',
  ts: 'typescript',
  tsx: 'typescript',
  h: 'c',
  c: 'c',
  hpp: 'cpp',
  cpp: 'cpp',
  py: 'python',
  rs: 'rust',
  java: 'java',
  go: 'go',
  cs: 'c_sharp',
  rb: 'ruby',
  php: 'php',
  swift: 'swift',
  css: 'css',
  sol: 'solidity',
};
