export const ext2lang = {
  vue: 'javascript',
  cjs: 'javascript',
  js: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  h: 'c',
  c: 'c',
  hpp: 'cpp',
  cpp: 'cpp',
  py: 'python',
  rs: 'rust',
  java: 'java',
  go: 'go',
  cs: 'c_sharp',
  rb: 'ruby',
  php: 'php',
  swift: 'swift',
};
